### ISSUE TITLE
JSON data submitted isn't as expected

### ISSUE THREAD

**Issue by coliff** [keithhackbarth/submitAsJSON#1]
Hey there - thanks for sharing this code! I've been testing it and see that the form submission looks like this:
```
{"api_key":"example","id":"hello@example.com": "}
```
however, this looks invalid and I'd have expected it to be like:
```
{"api_key":"example","id":"hello@example.com"}
```
Is the submitted JSON I am getting in the expected format?

Do you know how to adapt to strip the last `: "` ?

**Comment by keithhackbarth** [comment]
Yeah, I can look into it. Do you have a simple code example to reproduce issue?

**Comment by coliff** [comment]
sorry - was an error on my end. got it resolved now. thanks :-)
